version: '3'

services:
  nginx:
    build:
      context: ./nginx/
    container_name: simple-nginx
    volumes:
      - ./nginx/html:/var/docker/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - php

  php:
    build:
      context: ./php-fpm/
    container_name: simple-php
    
