version: '3'

services:
  nginx:
    build:
      context: ./nginx/
    container_name: simple-ngin
    volumes:
      - ./nginx/html:/var/docker/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

